version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
  web:
    build: .
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - ACTIONNETWORK_API_KEYS
      - DJANGO_SETTINGS_MODULE=config.settings.docker
    networks:
      - main
    depends_on:
      - db
networks:
  main:
