version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
  web:
    build: .
    image: server
    stdin_open: true
    tty: true
    volumes:  
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ACTIONNETWORK_API_KEYS
    networks:
      - main
    depends_on:
      - db
    command: bash init_db.sh

networks:
  main:
