[tool.poetry]
name = "stl-dsa"
version = "0.1.0"
description = "A Django + Wagtail based website for the St Louis Chapter of DSA"
authors = ["Tyler Schlichenmeyer <tyler.schlichenmeyer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.0"
Django = "^3.0.7"
django-allauth = "^0.42.0"
django-extensions = "^2.2.9"
django-crispy-forms = "^1.9.1"
django-environ = "^0.4.5"
whitenoise = "^5.1.0"
django-rest-framework = "^0.1.0"
wagtail = "^2.9"
django-phonenumber-field = {extras = ["phonenumbers"], version = "^4.0.0"}
argon2-cffi = "^20.1.0"
selenium = "^3.141.0"
wagtailmenus = "^3.0.2"
django-anymail = "^8.1"
psycopg2 = "^2.8.6"
gunicorn = "^20.0.4"
django-redis = "^4.12.1"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^2.2"
psycopg2-binary = "^2.8.5"
pylint = "^2.6.0"
black = {version = "^20.8b1", allow-prereleases = true}
pytest = "^6.2.2"
pytest-django = "^4.1.0"
factory-boy = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
DJANGO_SETTINGS_MODULE = "config.settings.local"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
filterwarnings = "ignore::django.utils.deprecation.RemovedInDjango40Warning"
