[tool.poetry]
name = "stl-dsa"
version = "0.1.0"
description = "A Django + Wagtail based website for the St Louis Chapter of DSA"
authors = ["Tyler Schlichenmeyer <tyler.schlichenmeyer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.6"
django-allauth = "^0.45.0"
django-extensions = "^2.2.9"
django-crispy-forms = "^1.9.1"
django-environ = "^0.4.5"
whitenoise = "^5.1.0"
django-rest-framework = "^0.1.0"
wagtail = "^2.14.1"
django-phonenumber-field = { extras = ["phonenumbers"], version = "^4.0.0" }
argon2-cffi = "^20.1.0"
selenium = "^3.141.0"
wagtailmenus = "^3.0.2"
django-anymail = "^8.1"
psycopg2 = "^2.8.6"
gunicorn = "^20.0.4"
django-redis = "^4.12.1"
django-scheduler = "^0.9.3"
wagtail-blocks = "^0.7.2"
wagtailfontawesome = "^1.2.1"
django-seed = "^0.2.2"
django-haystack = "^3.0"
elasticsearch = "^2.0"
requests = "^2.26.0"
pytest-django = "^4.4.0"
vcrpy = "^4.1.1"
python-dateutil = "^2.8.2"
django-configurations = "^2.2"
dj-database-url = "^0.5.0"
django-cache-url = "^3.2.3"

[tool.poetry.dev-dependencies]
psycopg2-binary = "^2.8.5"
pytest-django = "^4.1.0"
factory-boy = "^3.2.0"
pytest-vcr = "^1.0.2"
black = "^20.8b1"
django-seed = "^0.2.2"
Faker = "^8.10.1"
pytest-selenium = "^2.0.1"
pytest = "^6.2.4"
flake8 = "^3.9.2"
flakehell = "^0.9.0"
django-debug-toolbar = "^3.2.2"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango40Warning",
    "ignore::django.utils.deprecation.RemovedInDjango41Warning"
]

[tool.flakehell]
exclude = ["README.rst", "README.md",]
format = "colored"
max_line_length = 133
show_source = true
whitelist = "../../allowlist.txt"
extended_default_ignore = []

[tool.flakehell.plugins]
flake8-bandit = ["+*", "-S322"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-docstrings = ["+*"]
flake8-eradicate = ["+*"]
flake8-isort = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
flake8-spellcheck = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]

[tool.flakehell.exceptions."**/migrations/**"]
pycodestyle = ["-E501", "-F405"]

[build-system]
requires = ["poetry>=1.1.6"]
build-backend = "poetry.masonry.api"
