name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0

      - name: Install Dependencies
        run: poetry install

      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DJANGO_CONFIG: Test
          DATABASE_URL: "postgres://github_actions:postgres@db:5432/postgres"
        run: poetry run pytest --disable-warnings
