# action.yml
name: 'Docker'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Pytest
    runs-on: ubuntu-latest 
    container:
      image: docker://schlich/stl-dsa_web:latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      run: |
          pytest
